[package]
name = "revault_net"
version = "0.0.1"
authors = ["JSwambo <jake.t.swambo@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.24", features = ["use-serde"]}
serde = { version = "1.0", features = ["derive"] }
revault_tx = {git = "https://github.com/re-vault/revault_tx", features = ["use-serde"]}
snow = {version = "0.7.2", features = ["libsodium-resolver"]}
byteorder = "1.3.4"

[dev-dependencies]
serde_json = "1.0.58"